insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1287,'AX-8 Carbon Helmets','Adult MX Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1310,'Naked Helmet','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1400,'FX-24 Solid Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1417,'FX-90 Solid/Metallic Helmet','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1431,'FX-95 Solid Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1448,'Strike Ops Solid Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1521,'Airmada Solid Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1545,'Alliance GT Solid Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1584,'Variant Battlescar Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1586,'Variant Construct Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1652,'Corsa 500 Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1656,'Corsa Racetrack Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1675,'K-3SV Bulega Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1684,'K-3SV Marini Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1690,'K-3SV Simoncelli Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1692,'K-3SV Tartaruga Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1708,'K3 Chicken Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1711,'K3 Dream Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1717,'K3 Solid Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1750,'GT Veloce Gravity Helmet','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1751,'GT Veloce Helmet','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1752,'GT Veloce GTX Helmet','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (1773,'Gringo Solids/Metallics Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (22471,'Lane Splitter Helmet','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (24975,'Alliance Solid Helmet','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (2659,'Ace Solid Helmets','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (2674,'RP60 Metal Helmet','Adult Street Helmets');
insert into LEMANS.DIGITAL.PRODUCT (product_id, product_name, category_name) values (2699,'Bonanza Helmet','Adult Street Helmets');
